app:
    data_dir: C:\Users\SERTY\AppData\Roaming\ClipQueue
    silent: false
hotkeys:
    toggle_queue: Alt+C
    paste_next: Alt+V
clipboard:
    watch_debounce_ms: 30
    paste_delay_ms: 150
    restore_delay_ms: 1000
queue:
    default_order: LIFO
macros:
    - name: "321312"
      hotkey: VOLUMEDOWN
      signature: sig:AQAACgCuAAAAEQAAAAAB
      text: уцйуйцу
      mode: type
