app:
    data_dir: .
    silent: false
hotkeys:
    toggle_queue: CTRL+ALT+C
    paste_next: CTRL+ALT+V
clipboard:
    watch_debounce_ms: 30
    paste_delay_ms: 50
    restore_delay_ms: 1000
queue:
    default_order: FIFO
macros:
    CTRL+ALT+Q:
        text: 213цйуйцwqeqw211
        mode: paste
    CTRL+ALT+W:
        text: 21312цйуйцуwqeqw
        mode: type
