app:
    data_dir: .
    silent: false
hotkeys:
    toggle_queue: sig:AQADCgBXABEAAAAAAAAB
    paste_next: sig:AQADCgBWAC8AAAAAAAAB
    toggle_queue_display: Ctrl+Alt+W
    paste_next_display: Ctrl+Alt+V
clipboard:
    watch_debounce_ms: 30
    paste_delay_ms: 50
    restore_delay_ms: 250
queue:
    default_order: LIFO
features:
    enable_queue: false
    enable_clipboard: false
    enable_macros: true
    enable_lab: false
macros: []
